[Paths]
# Base directory where datasets and other data may reside
BASE_DIR = D:\model_train

# Directory specifically containing model files (.pt, .onnx, etc)
# If left blank or missing, it will fallback to BASE_DIR
MODELS_DIR = D:\model_train\models

# The directory where the active dataset will be saved
# By default, it will save in BASE_DIR/dataset_default
# OUTPUT_DIR = D:\model_train\dataset_default

[Settings]
# Default confidence threshold for YOLO inference
CONF_THRESH = 0.25
