[Paths]
# Base directory where datasets and other data may reside
BASE_DIR = ./datasets

# Directory specifically containing model files (.pt, .onnx, etc)
# If left blank or missing, it will fallback to BASE_DIR
MODELS_DIR = ./models

# The directory where the active dataset will be saved
# By default, it will save in BASE_DIR/dataset_<name>
# OUTPUT_DIR = ./datasets/dataset_default

[Settings]
# Default confidence threshold for YOLO inference
CONF_THRESH = 0.25
